/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aber
 */
public class KonverterSuhu extends javax.swing.JFrame {
    public Double input;
    public Double celcius;
    public Double fahrenheit;
    public Double reamur;
    public Double kelvin;
    public String hasilcelcius;
    public String hasilfahrenheit;
    public String hasilreamur;
    public String hasilkelvin;

    /**
     * Creates new form KonverterSuhu
     */
    public KonverterSuhu() {
        initComponents();
    }
    
    public void celcius(){
        input=Double.parseDouble(txtAwal.getText());
        
        celcius=input;
        fahrenheit=celcius*1.8+32;
        reamur=celcius*0.8;
        kelvin=celcius+273.15;
        
        //array[] 
        
        hasilcelcius=Double.toString(celcius);
        txtCelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtFahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtReamur.setText(hasilreamur);
        
        hasilkelvin=Double.toString(kelvin);
        txtKelvin.setText(hasilkelvin);
        //return[]//return array
    }
    
    public void fahrenheit(){
        input=Double.parseDouble(txtAwal.getText());
        
        fahrenheit=input;
        celcius=(fahrenheit-32)/1.8;
        reamur=(fahrenheit-32)/2.25;
        kelvin=(fahrenheit+459.67)/1.8;
        
        hasilcelcius=Double.toString(celcius);
        txtCelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtFahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtReamur.setText(hasilreamur);
        
        hasilkelvin=Double.toString(kelvin);
        txtKelvin.setText(hasilkelvin);
        
        
    }
    
    public void reamur(){
        input=Double.parseDouble(txtAwal.getText());
        
        reamur=input;
        celcius=reamur/0.8;
        fahrenheit=(reamur*2.25)+32;
        kelvin=reamur/0.8+273.15;
        
        
        hasilcelcius=Double.toString(celcius);
        txtCelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtFahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtReamur.setText(hasilreamur);
        
        hasilkelvin=Double.toString(kelvin);
        txtKelvin.setText(hasilkelvin);
    }
    
    public void kelvin(){
        input=Double.parseDouble(txtAwal.getText());
        
        kelvin=input;
        celcius=kelvin-273.15;
        fahrenheit=kelvin*1.8-459.67;
        reamur=(kelvin-273.15)*0.8;
        
        
        hasilcelcius=Double.toString(celcius);
        txtCelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtFahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtReamur.setText(hasilreamur);
        
        hasilkelvin=Double.toString(kelvin);
        txtKelvin.setText(hasilkelvin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAwal = new javax.swing.JTextField();
        rbCelcius = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCelcius = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        txtReamur = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 370));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel1.setText("INPUT TEMPERATURE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 160, 30);

        txtAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAwalActionPerformed(evt);
            }
        });
        getContentPane().add(txtAwal);
        txtAwal.setBounds(180, 70, 300, 30);

        rbCelcius.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rbCelcius.setText("Celcius");
        rbCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelciusActionPerformed(evt);
            }
        });
        getContentPane().add(rbCelcius);
        rbCelcius.setBounds(180, 120, 70, 23);

        rbFahrenheit.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rbFahrenheit.setText("Fahrenheit");
        rbFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFahrenheitActionPerformed(evt);
            }
        });
        getContentPane().add(rbFahrenheit);
        rbFahrenheit.setBounds(250, 120, 90, 23);

        rbReamur.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rbReamur.setText("Reamur");
        rbReamur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReamurActionPerformed(evt);
            }
        });
        getContentPane().add(rbReamur);
        rbReamur.setBounds(340, 120, 70, 23);

        rbKelvin.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        rbKelvin.setText("Kelvin");
        getContentPane().add(rbKelvin);
        rbKelvin.setBounds(410, 120, 70, 23);

        btnKonversi.setBackground(new java.awt.Color(0, 255, 0));
        btnKonversi.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 10)); // NOI18N
        btnKonversi.setText("CONVERT");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKonversi);
        btnKonversi.setBounds(200, 160, 85, 30);

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(null);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(330, 160, 80, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 48, 390, 2);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setText("CONVERSIONS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 210, 45);

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel3.setText("Celcius");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 240, 56, 30);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel4.setText("Fahrenheit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 280, 80, 30);

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel6.setText("Reamur");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 320, 70, 30);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel5.setText("Kelvin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 360, 60, 30);
        getContentPane().add(txtCelcius);
        txtCelcius.setBounds(120, 240, 181, 30);
        getContentPane().add(txtFahrenheit);
        txtFahrenheit.setBounds(120, 280, 181, 30);
        getContentPane().add(txtReamur);
        txtReamur.setBounds(120, 320, 181, 30);
        getContentPane().add(txtKelvin);
        txtKelvin.setBounds(120, 360, 181, 30);

        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 26)); // NOI18N
        jLabel7.setText("TEMPERATURE CONVERTER");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 20, 340, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aber\\Desktop\\red-sunset-warm-weather-temperature-png-29.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 190, 230, 230);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(4, 0, 0, 430);

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\fira\\CCIT\\Semester 3\\Quarter 5\\Project\\Project2(Testing)\\Images\\images.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAwalActionPerformed

    private void rbCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCelciusActionPerformed

    private void rbFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFahrenheitActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
        if(rbCelcius.isSelected()){
            celcius();
        }
        else if(rbFahrenheit.isSelected()){
            fahrenheit();
        }
        else if(rbReamur.isSelected()){
            reamur();
        }
        else if(rbKelvin.isSelected()){
            kelvin();
        }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAwal.setText("");
        txtCelcius.setText("");
        txtFahrenheit.setText("");
        txtReamur.setText("");
        txtKelvin.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbReamurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReamurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbReamurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonverterSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    private javax.swing.JTextField txtAwal;
    private javax.swing.JTextField txtCelcius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    private javax.swing.JTextField txtReamur;
    // End of variables declaration//GEN-END:variables
}
